apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.app }}-deployment
  namespace: {{ .Values.metadata.namespace }}
  labels:
    app: {{ .Values.metadata.app }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      app: {{ .Values.metadata.app }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app: {{ .Values.metadata.app }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: default
      containers:
        - name: {{ .Values.metadata.app }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: JASYPT_ENCRYPTOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jasypt-encryptor-secret
                  key: jasypt_password
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: {{ .Values.metadata.app }}-volume
            mountPath: "/config"
      volumes:
        - name: {{ .Values.metadata.app }}-volume
          configMap:
            name: {{ .Values.metadata.app }}-configmap